@startuml
skinparam style strictuml
skinparam classAttributeIconSize 0

' Interfaces

interface WorkerInterface <<Remote>>

' Klassen
class Bootstrap
class GUI
class Controller
class MandelbrotCalculator
class WorkerImpl
class WorkerServer

' Beziehungen

GUI --> Controller : uses
GUI --> Bootstrap : uses
Controller ..|> WorkerInterface : uses
Controller ..|> WorkerImpl : calls per RMI
WorkerImpl --> WorkerInterface : impelements
WorkerImpl --> MandelbrotCalculator : uses
WorkerServer -->Bootstrap : uses
WorkerServer --> WorkerImpl : starts

@enduml
